FROM node:20

RUN apt-get update && apt-get install -y openssl

RUN curl -fsSL https://bun.sh/install | bash \
    && ln -s /root/.bun/bin/bun /usr/local/bin/bun

WORKDIR /app

COPY bun.lockb package.json ./
RUN bun install

COPY . .

# ลบของเก่าก่อน generate ใหม่
RUN rm -rf node_modules/.prisma \
    && rm -rf src/generated/prisma-client \
    && rm -rf node_modules/@prisma/client

RUN npx prisma generate

ENV PORT=3001

CMD ["bun", "run", "src/index.ts"]